package ontology

// Vertex type constants from the ontology specification.
const (
	Artifact       VertexType = "Artifact"
	Revision       VertexType = "Revision"
	Agent          VertexType = "Agent"
	Human          VertexType = "Human"
	Prompt         VertexType = "Prompt"
	Model          VertexType = "Model"
	Tool           VertexType = "Tool"
	Execution      VertexType = "Execution"
	Observation    VertexType = "Observation"
	Evaluation     VertexType = "Evaluation"
	Policy         VertexType = "Policy"
	Dataset        VertexType = "Dataset"
	Environment    VertexType = "Environment"
	Intent         VertexType = "Intent"
	Claim          VertexType = "Claim"
	Proof          VertexType = "Proof"
	Task           VertexType = "Task"
	BranchSelector VertexType = "BranchSelector"
	MergeWitness   VertexType = "MergeWitness"
	Release        VertexType = "Release"
	Capability     VertexType = "Capability"
	Certificate    VertexType = "Certificate"
	Conflict       VertexType = "Conflict"
	ProjectionSpec VertexType = "ProjectionSpec"
)

// Edge type constants from the ontology specification.
const (
	DependsOn    EdgeType = "depends_on"
	DerivedFrom  EdgeType = "derived_from"
	Executes     EdgeType = "executes"
	AuthoredBy   EdgeType = "authored_by"
	ApprovedBy   EdgeType = "approved_by"
	EvaluatedBy  EdgeType = "evaluated_by"
	Constrains   EdgeType = "constrains"
	Supersedes   EdgeType = "supersedes"
	Observes     EdgeType = "observes"
	Proves       EdgeType = "proves"
	Refutes      EdgeType = "refutes"
	Calls        EdgeType = "calls"
	Materializes EdgeType = "materializes"
	Targets      EdgeType = "targets"
	BelongsTo    EdgeType = "belongs_to"
	ForksFrom    EdgeType = "forks_from"
	MergesInto   EdgeType = "merges_into"
	Selects      EdgeType = "selects"
	Binds        EdgeType = "binds"
	TracesTo     EdgeType = "traces_to"
	Justifies    EdgeType = "justifies"
	Violates     EdgeType = "violates"
	Satisfies    EdgeType = "satisfies"
	Certifies    EdgeType = "certifies"
)
